#user  nginx;
worker_processes  4;
#daemon off;

pid        /nginx/tmp/nginx.pid;

events {
    worker_connections  1024;
}

http {
    client_body_temp_path /nginx/tmp 1 2;
    proxy_temp_path /nginx/tmp 1 2;
    fastcgi_temp_path /nginx/tmp 1 2;
    uwsgi_temp_path /nginx/tmp 1 2;
    scgi_temp_path /nginx/tmp 1 2;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Switch logging to console out to view via Docker
    access_log /dev/stdout;
    error_log /dev/stderr;

    sendfile        on;
    keepalive_timeout  65;
    
    include /etc/nginx/sites-available/*.conf;
}